spring.datasource.url=jdbc:sqlite:dev-integration.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

comments.service.url=http://localhost:8081
