server.port=8082

spring.datasource.url=jdbc:sqlite:favorites-service.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

spring.jackson.deserialization.UNWRAP_ROOT_VALUE=true

monolith.url=http://localhost:8080

mybatis.configuration.cache-enabled=true
mybatis.configuration.default-statement-timeout=3000
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.use-generated-keys=true
mybatis.type-handlers-package=io.spring.favoritesservice.infrastructure.mybatis
mybatis.mapper-locations=mapper/*.xml
