server:
  port: 8085
spring:
  application:
    name: product-catalog-service
  datasource:
    url: jdbc:postgresql://localhost:5432/rm_product
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
jwt:
  secret: ${JWT_SECRET:rm-default-secret-key-for-development-only-change-in-production-1234567890}
