spring.datasource.url=jdbc:sqlite:file:comments_test?mode=memory&cache=shared
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.minimum-idle=1
monolith.service.url=http://localhost:8080
