server.port=8081
spring.application.name=article-service

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:realworld}?currentSchema=article_schema
spring.datasource.username=${DB_USER:realworld}
spring.datasource.password=${DB_PASSWORD:realworld}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.schemas=article_schema
spring.flyway.locations=classpath:db/migration

spring.jackson.deserialization.UNWRAP_ROOT_VALUE=true

jwt.secret=${JWT_SECRET}

user-service.url=${USER_SERVICE_URL:http://user-service:8080}

mybatis.configuration.cache-enabled=true
mybatis.configuration.default-statement-timeout=3000
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.use-generated-keys=true
mybatis.type-handlers-package=io.spring.common.mybatis
mybatis.mapper-locations=mapper/*.xml

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
