"""Seed realistic Indian stock data for GDF-12 screening.

Includes a mix of strong defensive picks, moderate candidates, and weaker stocks
across FMCG, Pharma, IT, Banking, Auto, Energy, Utilities, and other sectors.
"""

from sqlalchemy.orm import Session

from app.models.stock import Stock

SEED_STOCKS = [
    # === STRONG DEFENSIVE CANDIDATES (should score 9-12) ===
    {
        "symbol": "HINDUNILVR", "name": "Hindustan Unilever Ltd",
        "sector": "FMCG", "industry": "Personal Care", "exchange": "NSE",
        "current_price": 2380, "high_52w": 2860, "low_52w": 2170,
        "market_cap_cr": 559000, "sales_cr": 60580, "net_profit_cr": 10280,
        "profit_years_positive": 10,
        "has_strong_brand": True, "has_cost_advantage": True,
        "has_regulatory_barrier": False, "has_dominant_share": True,
        "moat_description": "India's largest FMCG company with 50+ power brands",
        "debt_to_equity": 0.0, "interest_coverage": 150.0,
        "roe": 38.5, "roce": 49.2,
        "ocf_positive_years": 10, "ocf_cr": 11200, "ocf_tracks_profit": True,
        "pe_ratio": 54.4, "pe_5y_avg": 62.0,
        "eps": 43.7, "book_value": 113.5,
        "pb_ratio": 21.0, "sector_avg_pb": 15.0,
        "promoter_holding_pct": 61.9, "promoter_pledge_pct": 0.0,
        "dividend_years": 10, "dividend_yield": 1.72,
        "price_flat_months": 18, "profit_growing": True, "volume_rising": True,
        "is_defensive_sector": True,
    },
    {
        "symbol": "TCS", "name": "Tata Consultancy Services Ltd",
        "sector": "IT Services", "industry": "IT Consulting", "exchange": "NSE",
        "current_price": 3450, "high_52w": 4260, "low_52w": 3060,
        "market_cap_cr": 1248000, "sales_cr": 240000, "net_profit_cr": 47800,
        "profit_years_positive": 10,
        "has_strong_brand": True, "has_cost_advantage": True,
        "has_regulatory_barrier": False, "has_dominant_share": True,
        "moat_description": "India's largest IT company, global top-10 IT services firm",
        "debt_to_equity": 0.08, "interest_coverage": 85.0,
        "roe": 52.0, "roce": 67.0,
        "ocf_positive_years": 10, "ocf_cr": 52000, "ocf_tracks_profit": True,
        "pe_ratio": 26.1, "pe_5y_avg": 30.5,
        "eps": 132.2, "book_value": 254.0,
        "pb_ratio": 13.6, "sector_avg_pb": 10.0,
        "promoter_holding_pct": 72.3, "promoter_pledge_pct": 0.0,
        "dividend_years": 10, "dividend_yield": 1.65,
        "price_flat_months": 12, "profit_growing": True, "volume_rising": False,
        "is_defensive_sector": True,
    },
    {
        "symbol": "INFY", "name": "Infosys Ltd",
        "sector": "IT Services", "industry": "IT Consulting", "exchange": "NSE",
        "current_price": 1520, "high_52w": 1960, "low_52w": 1360,
        "market_cap_cr": 631000, "sales_cr": 163000, "net_profit_cr": 27200,
        "profit_years_positive": 10,
        "has_strong_brand": True, "has_cost_advantage": True,
        "has_regulatory_barrier": False, "has_dominant_share": False,
        "moat_description": "Second largest Indian IT company, strong digital capabilities",
        "debt_to_equity": 0.1, "interest_coverage": 72.0,
        "roe": 33.5, "roce": 42.8,
        "ocf_positive_years": 10, "ocf_cr": 24000, "ocf_tracks_profit": True,
        "pe_ratio": 23.2, "pe_5y_avg": 27.0,
        "eps": 65.5, "book_value": 195.5,
        "pb_ratio": 7.8, "sector_avg_pb": 10.0,
        "promoter_holding_pct": 14.8, "promoter_pledge_pct": 0.0,
        "dividend_years": 10, "dividend_yield": 2.35,
        "price_flat_months": 8, "profit_growing": True, "volume_rising": True,
        "is_defensive_sector": True,
    },
    {
        "symbol": "NESTLEIND", "name": "Nestle India Ltd",
        "sector": "FMCG", "industry": "Packaged Foods", "exchange": "NSE",
        "current_price": 2280, "high_52w": 2780, "low_52w": 2050,
        "market_cap_cr": 220000, "sales_cr": 19200, "net_profit_cr": 2780,
        "profit_years_positive": 10,
        "has_strong_brand": True, "has_cost_advantage": False,
        "has_regulatory_barrier": False, "has_dominant_share": True,
        "moat_description": "Iconic brands Maggi, KitKat, Nescafe — dominant in packaged foods",
        "debt_to_equity": 0.05, "interest_coverage": 120.0,
        "roe": 108.0, "roce": 138.0,
        "ocf_positive_years": 10, "ocf_cr": 3100, "ocf_tracks_profit": True,
        "pe_ratio": 65.0, "pe_5y_avg": 72.0,
        "eps": 35.1, "book_value": 32.5,
        "pb_ratio": 70.2, "sector_avg_pb": 15.0,
        "promoter_holding_pct": 63.2, "promoter_pledge_pct": 0.0,
        "dividend_years": 10, "dividend_yield": 1.45,
        "price_flat_months": 15, "profit_growing": True, "volume_rising": False,
        "is_defensive_sector": True,
    },
    {
        "symbol": "SUNPHARMA", "name": "Sun Pharmaceutical Industries Ltd",
        "sector": "Pharma", "industry": "Pharmaceuticals", "exchange": "NSE",
        "current_price": 1710, "high_52w": 1960, "low_52w": 1220,
        "market_cap_cr": 410000, "sales_cr": 49800, "net_profit_cr": 10200,
        "profit_years_positive": 9,
        "has_strong_brand": True, "has_cost_advantage": True,
        "has_regulatory_barrier": True, "has_dominant_share": True,
        "moat_description": "India's largest pharma company, strong specialty pipeline",
        "debt_to_equity": 0.08, "interest_coverage": 42.0,
        "roe": 17.2, "roce": 20.5,
        "ocf_positive_years": 9, "ocf_cr": 9500, "ocf_tracks_profit": True,
        "pe_ratio": 36.8, "pe_5y_avg": 42.0,
        "eps": 46.5, "book_value": 270.0,
        "pb_ratio": 6.3, "sector_avg_pb": 6.5,
        "promoter_holding_pct": 54.5, "promoter_pledge_pct": 0.0,
        "dividend_years": 8, "dividend_yield": 0.58,
        "price_flat_months": 3, "profit_growing": True, "volume_rising": True,
        "is_defensive_sector": True,
    },
    {
        "symbol": "ITC", "name": "ITC Ltd",
        "sector": "FMCG", "industry": "Diversified FMCG / Tobacco", "exchange": "NSE",
        "current_price": 430, "high_52w": 500, "low_52w": 390,
        "market_cap_cr": 537000, "sales_cr": 70200, "net_profit_cr": 20100,
        "profit_years_positive": 10,
        "has_strong_brand": True, "has_cost_advantage": True,
        "has_regulatory_barrier": True, "has_dominant_share": True,
        "moat_description": "Dominant tobacco + growing FMCG brands (Bingo, Aashirvaad, Sunfeast)",
        "debt_to_equity": 0.0, "interest_coverage": 200.0,
        "roe": 28.5, "roce": 36.8,
        "ocf_positive_years": 10, "ocf_cr": 18500, "ocf_tracks_profit": True,
        "pe_ratio": 26.7, "pe_5y_avg": 23.0,
        "eps": 16.1, "book_value": 56.5,
        "pb_ratio": 7.6, "sector_avg_pb": 15.0,
        "promoter_holding_pct": 0.0, "promoter_pledge_pct": 0.0,
        "dividend_years": 10, "dividend_yield": 3.12,
        "price_flat_months": 24, "profit_growing": True, "volume_rising": True,
        "is_defensive_sector": True,
    },
    {
        "symbol": "POWERGRID", "name": "Power Grid Corporation of India Ltd",
        "sector": "Utilities", "industry": "Power Transmission", "exchange": "NSE",
        "current_price": 285, "high_52w": 350, "low_52w": 210,
        "market_cap_cr": 265000, "sales_cr": 46000, "net_profit_cr": 16200,
        "profit_years_positive": 10,
        "has_strong_brand": False, "has_cost_advantage": True,
        "has_regulatory_barrier": True, "has_dominant_share": True,
        "moat_description": "Monopoly in inter-state power transmission, regulated returns",
        "debt_to_equity": 1.4, "interest_coverage": 3.2,
        "roe": 18.5, "roce": 12.8,
        "ocf_positive_years": 10, "ocf_cr": 32000, "ocf_tracks_profit": True,
        "pe_ratio": 16.4, "pe_5y_avg": 12.0,
        "eps": 17.4, "book_value": 94.0,
        "pb_ratio": 3.0, "sector_avg_pb": 3.5,
        "promoter_holding_pct": 51.3, "promoter_pledge_pct": 0.0,
        "dividend_years": 10, "dividend_yield": 3.85,
        "price_flat_months": 2, "profit_growing": True, "volume_rising": True,
        "is_defensive_sector": True,
    },
    {
        "symbol": "DABUR", "name": "Dabur India Ltd",
        "sector": "FMCG", "industry": "Personal Care / Ayurvedic", "exchange": "NSE",
        "current_price": 540, "high_52w": 650, "low_52w": 490,
        "market_cap_cr": 95700, "sales_cr": 12500, "net_profit_cr": 1920,
        "profit_years_positive": 10,
        "has_strong_brand": True, "has_cost_advantage": False,
        "has_regulatory_barrier": False, "has_dominant_share": False,
        "moat_description": "Strong Ayurveda brand portfolio — Dabur Chyawanprash, Real Juice",
        "debt_to_equity": 0.12, "interest_coverage": 32.0,
        "roe": 24.5, "roce": 28.0,
        "ocf_positive_years": 10, "ocf_cr": 2100, "ocf_tracks_profit": True,
        "pe_ratio": 49.8, "pe_5y_avg": 55.0,
        "eps": 10.8, "book_value": 44.2,
        "pb_ratio": 12.2, "sector_avg_pb": 15.0,
        "promoter_holding_pct": 67.4, "promoter_pledge_pct": 0.0,
        "dividend_years": 10, "dividend_yield": 1.10,
        "price_flat_months": 14, "profit_growing": True, "volume_rising": False,
        "is_defensive_sector": True,
    },
    {
        "symbol": "DRREDDY", "name": "Dr. Reddy's Laboratories Ltd",
        "sector": "Pharma", "industry": "Pharmaceuticals", "exchange": "NSE",
        "current_price": 1180, "high_52w": 1360, "low_52w": 980,
        "market_cap_cr": 98500, "sales_cr": 28500, "net_profit_cr": 4200,
        "profit_years_positive": 10,
        "has_strong_brand": True, "has_cost_advantage": True,
        "has_regulatory_barrier": True, "has_dominant_share": False,
        "moat_description": "Strong generics pipeline, US FDA approved facilities",
        "debt_to_equity": 0.15, "interest_coverage": 28.0,
        "roe": 19.8, "roce": 22.5,
        "ocf_positive_years": 9, "ocf_cr": 4800, "ocf_tracks_profit": True,
        "pe_ratio": 19.2, "pe_5y_avg": 24.0,
        "eps": 61.5, "book_value": 310.0,
        "pb_ratio": 3.8, "sector_avg_pb": 6.5,
        "promoter_holding_pct": 26.7, "promoter_pledge_pct": 0.0,
        "dividend_years": 9, "dividend_yield": 0.72,
        "price_flat_months": 6, "profit_growing": True, "volume_rising": True,
        "is_defensive_sector": True,
    },
    {
        "symbol": "GAIL", "name": "GAIL (India) Ltd",
        "sector": "Gas / Pipelines", "industry": "Natural Gas", "exchange": "NSE",
        "current_price": 178, "high_52w": 215, "low_52w": 120,
        "market_cap_cr": 117000, "sales_cr": 135000, "net_profit_cr": 10200,
        "profit_years_positive": 10,
        "has_strong_brand": False, "has_cost_advantage": True,
        "has_regulatory_barrier": True, "has_dominant_share": True,
        "moat_description": "India's largest natural gas pipeline operator, government-backed",
        "debt_to_equity": 0.18, "interest_coverage": 22.0,
        "roe": 14.8, "roce": 17.5,
        "ocf_positive_years": 10, "ocf_cr": 12500, "ocf_tracks_profit": True,
        "pe_ratio": 11.5, "pe_5y_avg": 14.0,
        "eps": 15.5, "book_value": 105.0,
        "pb_ratio": 1.7, "sector_avg_pb": 2.0,
        "promoter_holding_pct": 51.9, "promoter_pledge_pct": 0.0,
        "dividend_years": 10, "dividend_yield": 2.80,
        "price_flat_months": 7, "profit_growing": True, "volume_rising": True,
        "is_defensive_sector": True,
    },
    # === MODERATE CANDIDATES (should score 6-8) ===
    {
        "symbol": "HDFCBANK", "name": "HDFC Bank Ltd",
        "sector": "Banking", "industry": "Private Banks", "exchange": "NSE",
        "current_price": 1620, "high_52w": 1790, "low_52w": 1390,
        "market_cap_cr": 1230000, "sales_cr": 280000, "net_profit_cr": 58000,
        "profit_years_positive": 10,
        "has_strong_brand": True, "has_cost_advantage": False,
        "has_regulatory_barrier": True, "has_dominant_share": True,
        "moat_description": "India's largest private bank, best-in-class asset quality",
        "debt_to_equity": 6.8, "interest_coverage": 1.8,
        "roe": 16.8, "roce": 8.2,
        "ocf_positive_years": 8, "ocf_cr": 45000, "ocf_tracks_profit": True,
        "pe_ratio": 19.2, "pe_5y_avg": 22.0,
        "eps": 84.4, "book_value": 502.0,
        "pb_ratio": 3.2, "sector_avg_pb": 3.0,
        "promoter_holding_pct": 26.0, "promoter_pledge_pct": 0.0,
        "dividend_years": 10, "dividend_yield": 1.18,
        "price_flat_months": 8, "profit_growing": True, "volume_rising": True,
        "is_defensive_sector": False,
    },
    {
        "symbol": "RELIANCE", "name": "Reliance Industries Ltd",
        "sector": "Energy", "industry": "Diversified Conglomerate", "exchange": "NSE",
        "current_price": 1260, "high_52w": 1600, "low_52w": 1150,
        "market_cap_cr": 1700000, "sales_cr": 975000, "net_profit_cr": 79800,
        "profit_years_positive": 10,
        "has_strong_brand": True, "has_cost_advantage": True,
        "has_regulatory_barrier": False, "has_dominant_share": True,
        "moat_description": "Largest Indian conglomerate, Jio platform, retail dominance",
        "debt_to_equity": 0.38, "interest_coverage": 8.5,
        "roe": 9.8, "roce": 11.2,
        "ocf_positive_years": 10, "ocf_cr": 98000, "ocf_tracks_profit": True,
        "pe_ratio": 24.5, "pe_5y_avg": 28.0,
        "eps": 51.4, "book_value": 524.0,
        "pb_ratio": 2.4, "sector_avg_pb": 2.0,
        "promoter_holding_pct": 50.3, "promoter_pledge_pct": 0.0,
        "dividend_years": 10, "dividend_yield": 0.32,
        "price_flat_months": 14, "profit_growing": False, "volume_rising": True,
        "is_defensive_sector": False,
    },
    {
        "symbol": "BAJFINANCE", "name": "Bajaj Finance Ltd",
        "sector": "NBFC", "industry": "Consumer Finance", "exchange": "NSE",
        "current_price": 6800, "high_52w": 8200, "low_52w": 6200,
        "market_cap_cr": 420000, "sales_cr": 52000, "net_profit_cr": 14800,
        "profit_years_positive": 10,
        "has_strong_brand": True, "has_cost_advantage": False,
        "has_regulatory_barrier": True, "has_dominant_share": False,
        "moat_description": "India's leading consumer NBFC, strong distribution moat",
        "debt_to_equity": 3.8, "interest_coverage": 2.5,
        "roe": 22.5, "roce": 12.8,
        "ocf_positive_years": 7, "ocf_cr": 8500, "ocf_tracks_profit": False,
        "pe_ratio": 28.4, "pe_5y_avg": 45.0,
        "eps": 239.4, "book_value": 1065.0,
        "pb_ratio": 6.4, "sector_avg_pb": 4.0,
        "promoter_holding_pct": 54.8, "promoter_pledge_pct": 2.5,
        "dividend_years": 8, "dividend_yield": 0.44,
        "price_flat_months": 3, "profit_growing": True, "volume_rising": False,
        "is_defensive_sector": False,
    },
    {
        "symbol": "MARUTI", "name": "Maruti Suzuki India Ltd",
        "sector": "Automobile", "industry": "Passenger Vehicles", "exchange": "NSE",
        "current_price": 11800, "high_52w": 13200, "low_52w": 9800,
        "market_cap_cr": 370000, "sales_cr": 140000, "net_profit_cr": 13200,
        "profit_years_positive": 9,
        "has_strong_brand": True, "has_cost_advantage": True,
        "has_regulatory_barrier": False, "has_dominant_share": True,
        "moat_description": "India's largest carmaker, 42% passenger vehicle market share",
        "debt_to_equity": 0.02, "interest_coverage": 95.0,
        "roe": 16.0, "roce": 21.5,
        "ocf_positive_years": 8, "ocf_cr": 15000, "ocf_tracks_profit": True,
        "pe_ratio": 28.0, "pe_5y_avg": 35.0,
        "eps": 421.4, "book_value": 2630.0,
        "pb_ratio": 4.5, "sector_avg_pb": 5.0,
        "promoter_holding_pct": 56.4, "promoter_pledge_pct": 0.0,
        "dividend_years": 8, "dividend_yield": 0.85,
        "price_flat_months": 2, "profit_growing": True, "volume_rising": True,
        "is_defensive_sector": False,
    },
    {
        "symbol": "WIPRO", "name": "Wipro Ltd",
        "sector": "IT Services", "industry": "IT Consulting", "exchange": "NSE",
        "current_price": 420, "high_52w": 570, "low_52w": 380,
        "market_cap_cr": 219000, "sales_cr": 90000, "net_profit_cr": 11300,
        "profit_years_positive": 10,
        "has_strong_brand": True, "has_cost_advantage": False,
        "has_regulatory_barrier": False, "has_dominant_share": False,
        "moat_description": "Top-5 Indian IT company, strong consulting presence",
        "debt_to_equity": 0.2, "interest_coverage": 20.0,
        "roe": 16.5, "roce": 19.8,
        "ocf_positive_years": 10, "ocf_cr": 13000, "ocf_tracks_profit": True,
        "pe_ratio": 19.4, "pe_5y_avg": 21.0,
        "eps": 21.6, "book_value": 131.0,
        "pb_ratio": 3.2, "sector_avg_pb": 10.0,
        "promoter_holding_pct": 72.9, "promoter_pledge_pct": 0.0,
        "dividend_years": 10, "dividend_yield": 0.24,
        "price_flat_months": 10, "profit_growing": False, "volume_rising": True,
        "is_defensive_sector": True,
    },
    {
        "symbol": "ASIANPAINT", "name": "Asian Paints Ltd",
        "sector": "Chemicals", "industry": "Decorative Paints", "exchange": "NSE",
        "current_price": 2750, "high_52w": 3540, "low_52w": 2440,
        "market_cap_cr": 264000, "sales_cr": 35700, "net_profit_cr": 5100,
        "profit_years_positive": 10,
        "has_strong_brand": True, "has_cost_advantage": True,
        "has_regulatory_barrier": False, "has_dominant_share": True,
        "moat_description": "55% market share in decorative paints, strongest dealer network",
        "debt_to_equity": 0.15, "interest_coverage": 38.0,
        "roe": 28.2, "roce": 36.5,
        "ocf_positive_years": 10, "ocf_cr": 5800, "ocf_tracks_profit": True,
        "pe_ratio": 51.8, "pe_5y_avg": 72.0,
        "eps": 53.1, "book_value": 188.5,
        "pb_ratio": 14.6, "sector_avg_pb": 8.0,
        "promoter_holding_pct": 52.6, "promoter_pledge_pct": 0.0,
        "dividend_years": 10, "dividend_yield": 0.75,
        "price_flat_months": 20, "profit_growing": True, "volume_rising": True,
        "is_defensive_sector": False,
    },
    {
        "symbol": "COALINDIA", "name": "Coal India Ltd",
        "sector": "Mining", "industry": "Coal Mining", "exchange": "NSE",
        "current_price": 385, "high_52w": 490, "low_52w": 290,
        "market_cap_cr": 237000, "sales_cr": 142000, "net_profit_cr": 35200,
        "profit_years_positive": 10,
        "has_strong_brand": False, "has_cost_advantage": True,
        "has_regulatory_barrier": True, "has_dominant_share": True,
        "moat_description": "State monopoly on coal production, 80% of India's coal output",
        "debt_to_equity": 0.08, "interest_coverage": 65.0,
        "roe": 52.0, "roce": 62.5,
        "ocf_positive_years": 10, "ocf_cr": 28000, "ocf_tracks_profit": True,
        "pe_ratio": 6.7, "pe_5y_avg": 8.0,
        "eps": 57.5, "book_value": 110.5,
        "pb_ratio": 3.5, "sector_avg_pb": 4.0,
        "promoter_holding_pct": 63.1, "promoter_pledge_pct": 0.0,
        "dividend_years": 10, "dividend_yield": 6.50,
        "price_flat_months": 4, "profit_growing": False, "volume_rising": True,
        "is_defensive_sector": False,
    },
    {
        "symbol": "CIPLA", "name": "Cipla Ltd",
        "sector": "Pharma", "industry": "Pharmaceuticals", "exchange": "NSE",
        "current_price": 1420, "high_52w": 1680, "low_52w": 1080,
        "market_cap_cr": 115000, "sales_cr": 25800, "net_profit_cr": 3800,
        "profit_years_positive": 10,
        "has_strong_brand": True, "has_cost_advantage": True,
        "has_regulatory_barrier": True, "has_dominant_share": False,
        "moat_description": "Strong respiratory and anti-infective portfolio, Africa presence",
        "debt_to_equity": 0.05, "interest_coverage": 55.0,
        "roe": 16.8, "roce": 21.2,
        "ocf_positive_years": 10, "ocf_cr": 4200, "ocf_tracks_profit": True,
        "pe_ratio": 30.3, "pe_5y_avg": 32.0,
        "eps": 46.9, "book_value": 279.0,
        "pb_ratio": 5.1, "sector_avg_pb": 6.5,
        "promoter_holding_pct": 33.5, "promoter_pledge_pct": 0.0,
        "dividend_years": 9, "dividend_yield": 0.56,
        "price_flat_months": 1, "profit_growing": True, "volume_rising": True,
        "is_defensive_sector": True,
    },
    {
        "symbol": "NTPC", "name": "NTPC Ltd",
        "sector": "Utilities", "industry": "Power Generation", "exchange": "NSE",
        "current_price": 345, "high_52w": 420, "low_52w": 230,
        "market_cap_cr": 335000, "sales_cr": 178000, "net_profit_cr": 22500,
        "profit_years_positive": 10,
        "has_strong_brand": False, "has_cost_advantage": True,
        "has_regulatory_barrier": True, "has_dominant_share": True,
        "moat_description": "India's largest power generator, regulated cost-plus model",
        "debt_to_equity": 1.2, "interest_coverage": 3.5,
        "roe": 13.5, "roce": 10.2,
        "ocf_positive_years": 10, "ocf_cr": 35000, "ocf_tracks_profit": True,
        "pe_ratio": 14.9, "pe_5y_avg": 11.0,
        "eps": 23.2, "book_value": 172.0,
        "pb_ratio": 2.0, "sector_avg_pb": 3.5,
        "promoter_holding_pct": 51.1, "promoter_pledge_pct": 0.0,
        "dividend_years": 10, "dividend_yield": 2.45,
        "price_flat_months": 0, "profit_growing": True, "volume_rising": True,
        "is_defensive_sector": True,
    },
    {
        "symbol": "BRITANNIA", "name": "Britannia Industries Ltd",
        "sector": "FMCG", "industry": "Packaged Foods", "exchange": "NSE",
        "current_price": 5100, "high_52w": 5950, "low_52w": 4520,
        "market_cap_cr": 123000, "sales_cr": 16700, "net_profit_cr": 2080,
        "profit_years_positive": 10,
        "has_strong_brand": True, "has_cost_advantage": False,
        "has_regulatory_barrier": False, "has_dominant_share": True,
        "moat_description": "Dominant biscuit brand (Good Day, Marie Gold), growing dairy",
        "debt_to_equity": 0.35, "interest_coverage": 18.0,
        "roe": 54.0, "roce": 42.0,
        "ocf_positive_years": 9, "ocf_cr": 2200, "ocf_tracks_profit": True,
        "pe_ratio": 59.1, "pe_5y_avg": 58.0,
        "eps": 86.3, "book_value": 160.0,
        "pb_ratio": 31.9, "sector_avg_pb": 15.0,
        "promoter_holding_pct": 50.6, "promoter_pledge_pct": 0.0,
        "dividend_years": 10, "dividend_yield": 1.20,
        "price_flat_months": 10, "profit_growing": True, "volume_rising": False,
        "is_defensive_sector": True,
    },
    # === WEAKER CANDIDATES (should score 3-5) ===
    {
        "symbol": "TATAMOTORS", "name": "Tata Motors Ltd",
        "sector": "Automobile", "industry": "Commercial & Passenger Vehicles", "exchange": "NSE",
        "current_price": 640, "high_52w": 1080, "low_52w": 580,
        "market_cap_cr": 235000, "sales_cr": 435000, "net_profit_cr": 31500,
        "profit_years_positive": 6,
        "has_strong_brand": True, "has_cost_advantage": False,
        "has_regulatory_barrier": False, "has_dominant_share": False,
        "moat_description": "JLR acquisition gives global reach, EV push with Nexon",
        "debt_to_equity": 1.1, "interest_coverage": 3.8,
        "roe": 28.5, "roce": 14.8,
        "ocf_positive_years": 6, "ocf_cr": 38000, "ocf_tracks_profit": False,
        "pe_ratio": 7.5, "pe_5y_avg": 15.0,
        "eps": 85.3, "book_value": 300.0,
        "pb_ratio": 2.1, "sector_avg_pb": 5.0,
        "promoter_holding_pct": 46.4, "promoter_pledge_pct": 3.5,
        "dividend_years": 4, "dividend_yield": 0.31,
        "price_flat_months": 0, "profit_growing": False, "volume_rising": True,
        "is_defensive_sector": False,
    },
    {
        "symbol": "JSWSTEEL", "name": "JSW Steel Ltd",
        "sector": "Metals", "industry": "Steel", "exchange": "NSE",
        "current_price": 820, "high_52w": 1050, "low_52w": 710,
        "market_cap_cr": 200000, "sales_cr": 178000, "net_profit_cr": 12500,
        "profit_years_positive": 7,
        "has_strong_brand": False, "has_cost_advantage": True,
        "has_regulatory_barrier": False, "has_dominant_share": False,
        "moat_description": "India's largest private steelmaker, cost-efficient operations",
        "debt_to_equity": 0.95, "interest_coverage": 5.2,
        "roe": 15.2, "roce": 13.5,
        "ocf_positive_years": 8, "ocf_cr": 24000, "ocf_tracks_profit": True,
        "pe_ratio": 16.0, "pe_5y_avg": 18.0,
        "eps": 51.3, "book_value": 337.5,
        "pb_ratio": 2.4, "sector_avg_pb": 2.0,
        "promoter_holding_pct": 44.8, "promoter_pledge_pct": 12.0,
        "dividend_years": 5, "dividend_yield": 0.85,
        "price_flat_months": 0, "profit_growing": False, "volume_rising": False,
        "is_defensive_sector": False,
    },
    {
        "symbol": "ADANIENT", "name": "Adani Enterprises Ltd",
        "sector": "Infrastructure", "industry": "Diversified Infrastructure", "exchange": "NSE",
        "current_price": 2400, "high_52w": 3740, "low_52w": 2020,
        "market_cap_cr": 274000, "sales_cr": 96000, "net_profit_cr": 3400,
        "profit_years_positive": 8,
        "has_strong_brand": False, "has_cost_advantage": False,
        "has_regulatory_barrier": False, "has_dominant_share": False,
        "moat_description": "Diversified infrastructure play, incubation entity for Adani group",
        "debt_to_equity": 1.5, "interest_coverage": 2.8,
        "roe": 12.5, "roce": 9.8,
        "ocf_positive_years": 5, "ocf_cr": 4500, "ocf_tracks_profit": False,
        "pe_ratio": 80.6, "pe_5y_avg": 120.0,
        "eps": 29.8, "book_value": 238.0,
        "pb_ratio": 10.1, "sector_avg_pb": 4.0,
        "promoter_holding_pct": 72.6, "promoter_pledge_pct": 18.5,
        "dividend_years": 3, "dividend_yield": 0.04,
        "price_flat_months": 0, "profit_growing": True, "volume_rising": True,
        "is_defensive_sector": False,
    },
    {
        "symbol": "VEDL", "name": "Vedanta Ltd",
        "sector": "Mining", "industry": "Diversified Metals & Mining", "exchange": "NSE",
        "current_price": 420, "high_52w": 520, "low_52w": 220,
        "market_cap_cr": 156000, "sales_cr": 145000, "net_profit_cr": 15800,
        "profit_years_positive": 7,
        "has_strong_brand": False, "has_cost_advantage": True,
        "has_regulatory_barrier": False, "has_dominant_share": False,
        "moat_description": "Low-cost zinc and aluminium producer, but cyclical",
        "debt_to_equity": 1.8, "interest_coverage": 4.2,
        "roe": 35.0, "roce": 22.0,
        "ocf_positive_years": 7, "ocf_cr": 28000, "ocf_tracks_profit": False,
        "pe_ratio": 9.9, "pe_5y_avg": 12.0,
        "eps": 42.4, "book_value": 120.0,
        "pb_ratio": 3.5, "sector_avg_pb": 4.0,
        "promoter_holding_pct": 56.4, "promoter_pledge_pct": 25.0,
        "dividend_years": 6, "dividend_yield": 7.80,
        "price_flat_months": 0, "profit_growing": False, "volume_rising": True,
        "is_defensive_sector": False,
    },
    {
        "symbol": "ZOMATO", "name": "Zomato Ltd",
        "sector": "Internet", "industry": "Food Delivery Platform", "exchange": "NSE",
        "current_price": 175, "high_52w": 265, "low_52w": 110,
        "market_cap_cr": 155000, "sales_cr": 12100, "net_profit_cr": 350,
        "profit_years_positive": 2,
        "has_strong_brand": True, "has_cost_advantage": False,
        "has_regulatory_barrier": False, "has_dominant_share": True,
        "moat_description": "Duopoly in food delivery with Swiggy, Blinkit quick commerce",
        "debt_to_equity": 0.02, "interest_coverage": 15.0,
        "roe": 3.5, "roce": 4.2,
        "ocf_positive_years": 2, "ocf_cr": 800, "ocf_tracks_profit": True,
        "pe_ratio": 442.9, "pe_5y_avg": 0.0,
        "eps": 0.4, "book_value": 11.5,
        "pb_ratio": 15.2, "sector_avg_pb": 8.0,
        "promoter_holding_pct": 0.0, "promoter_pledge_pct": 0.0,
        "dividend_years": 0, "dividend_yield": 0.0,
        "price_flat_months": 0, "profit_growing": True, "volume_rising": True,
        "is_defensive_sector": False,
    },
    {
        "symbol": "PAYTM", "name": "One 97 Communications Ltd (Paytm)",
        "sector": "Fintech", "industry": "Digital Payments", "exchange": "NSE",
        "current_price": 680, "high_52w": 980, "low_52w": 320,
        "market_cap_cr": 43200, "sales_cr": 9200, "net_profit_cr": -1200,
        "profit_years_positive": 0,
        "has_strong_brand": True, "has_cost_advantage": False,
        "has_regulatory_barrier": False, "has_dominant_share": False,
        "moat_description": "Large user base but regulatory concerns and no path to profitability",
        "debt_to_equity": 0.05, "interest_coverage": -2.0,
        "roe": -18.0, "roce": -14.0,
        "ocf_positive_years": 1, "ocf_cr": -500, "ocf_tracks_profit": True,
        "pe_ratio": -36.0, "pe_5y_avg": 0.0,
        "eps": -18.9, "book_value": 105.0,
        "pb_ratio": 6.5, "sector_avg_pb": 4.0,
        "promoter_holding_pct": 9.1, "promoter_pledge_pct": 0.0,
        "dividend_years": 0, "dividend_yield": 0.0,
        "price_flat_months": 0, "profit_growing": False, "volume_rising": True,
        "is_defensive_sector": False,
    },
    # === MORE STOCKS FOR VARIETY ===
    {
        "symbol": "HCLTECH", "name": "HCL Technologies Ltd",
        "sector": "IT Services", "industry": "IT Consulting", "exchange": "NSE",
        "current_price": 1340, "high_52w": 1800, "low_52w": 1200,
        "market_cap_cr": 364000, "sales_cr": 109000, "net_profit_cr": 15800,
        "profit_years_positive": 10,
        "has_strong_brand": True, "has_cost_advantage": False,
        "has_regulatory_barrier": False, "has_dominant_share": False,
        "moat_description": "Top-3 Indian IT, strong infrastructure management practice",
        "debt_to_equity": 0.05, "interest_coverage": 48.0,
        "roe": 23.8, "roce": 30.5,
        "ocf_positive_years": 10, "ocf_cr": 18000, "ocf_tracks_profit": True,
        "pe_ratio": 23.0, "pe_5y_avg": 24.0,
        "eps": 58.3, "book_value": 245.0,
        "pb_ratio": 5.5, "sector_avg_pb": 10.0,
        "promoter_holding_pct": 60.8, "promoter_pledge_pct": 0.0,
        "dividend_years": 10, "dividend_yield": 3.80,
        "price_flat_months": 8, "profit_growing": True, "volume_rising": True,
        "is_defensive_sector": True,
    },
    {
        "symbol": "MARICO", "name": "Marico Ltd",
        "sector": "FMCG", "industry": "Personal Care / Hair Oil", "exchange": "NSE",
        "current_price": 580, "high_52w": 670, "low_52w": 480,
        "market_cap_cr": 75000, "sales_cr": 10100, "net_profit_cr": 1580,
        "profit_years_positive": 10,
        "has_strong_brand": True, "has_cost_advantage": False,
        "has_regulatory_barrier": False, "has_dominant_share": True,
        "moat_description": "Parachute coconut oil (60% share), Saffola, Digital-first brands",
        "debt_to_equity": 0.08, "interest_coverage": 42.0,
        "roe": 38.5, "roce": 45.2,
        "ocf_positive_years": 10, "ocf_cr": 1650, "ocf_tracks_profit": True,
        "pe_ratio": 47.5, "pe_5y_avg": 50.0,
        "eps": 12.2, "book_value": 31.7,
        "pb_ratio": 18.3, "sector_avg_pb": 15.0,
        "promoter_holding_pct": 59.0, "promoter_pledge_pct": 0.0,
        "dividend_years": 10, "dividend_yield": 1.38,
        "price_flat_months": 12, "profit_growing": True, "volume_rising": False,
        "is_defensive_sector": True,
    },
    {
        "symbol": "PIDILITIND", "name": "Pidilite Industries Ltd",
        "sector": "Chemicals", "industry": "Adhesives & Sealants", "exchange": "NSE",
        "current_price": 2680, "high_52w": 3180, "low_52w": 2340,
        "market_cap_cr": 136000, "sales_cr": 12800, "net_profit_cr": 2050,
        "profit_years_positive": 10,
        "has_strong_brand": True, "has_cost_advantage": True,
        "has_regulatory_barrier": False, "has_dominant_share": True,
        "moat_description": "Fevicol — 70%+ adhesives market share, iconic brand moat",
        "debt_to_equity": 0.02, "interest_coverage": 85.0,
        "roe": 26.5, "roce": 34.0,
        "ocf_positive_years": 10, "ocf_cr": 2300, "ocf_tracks_profit": True,
        "pe_ratio": 66.3, "pe_5y_avg": 75.0,
        "eps": 40.4, "book_value": 152.5,
        "pb_ratio": 17.6, "sector_avg_pb": 8.0,
        "promoter_holding_pct": 69.9, "promoter_pledge_pct": 0.0,
        "dividend_years": 10, "dividend_yield": 0.60,
        "price_flat_months": 15, "profit_growing": True, "volume_rising": False,
        "is_defensive_sector": False,
    },
    {
        "symbol": "SBIN", "name": "State Bank of India",
        "sector": "Banking", "industry": "Public Sector Banks", "exchange": "NSE",
        "current_price": 760, "high_52w": 912, "low_52w": 620,
        "market_cap_cr": 678000, "sales_cr": 420000, "net_profit_cr": 62000,
        "profit_years_positive": 8,
        "has_strong_brand": True, "has_cost_advantage": True,
        "has_regulatory_barrier": True, "has_dominant_share": True,
        "moat_description": "India's largest bank, CASA advantage, government-backed",
        "debt_to_equity": 13.5, "interest_coverage": 1.5,
        "roe": 20.5, "roce": 7.5,
        "ocf_positive_years": 6, "ocf_cr": 35000, "ocf_tracks_profit": False,
        "pe_ratio": 10.9, "pe_5y_avg": 12.0,
        "eps": 69.7, "book_value": 340.0,
        "pb_ratio": 2.2, "sector_avg_pb": 3.0,
        "promoter_holding_pct": 57.5, "promoter_pledge_pct": 0.0,
        "dividend_years": 10, "dividend_yield": 1.84,
        "price_flat_months": 4, "profit_growing": True, "volume_rising": True,
        "is_defensive_sector": False,
    },
    {
        "symbol": "TITAN", "name": "Titan Company Ltd",
        "sector": "Consumer Discretionary", "industry": "Jewellery & Watches", "exchange": "NSE",
        "current_price": 3150, "high_52w": 3890, "low_52w": 2920,
        "market_cap_cr": 280000, "sales_cr": 51500, "net_profit_cr": 3500,
        "profit_years_positive": 10,
        "has_strong_brand": True, "has_cost_advantage": False,
        "has_regulatory_barrier": False, "has_dominant_share": True,
        "moat_description": "Tanishq (dominant jewellery brand), Titan watches, strong retail",
        "debt_to_equity": 0.4, "interest_coverage": 12.0,
        "roe": 32.5, "roce": 28.0,
        "ocf_positive_years": 8, "ocf_cr": 3200, "ocf_tracks_profit": False,
        "pe_ratio": 80.0, "pe_5y_avg": 75.0,
        "eps": 39.4, "book_value": 121.0,
        "pb_ratio": 26.0, "sector_avg_pb": 10.0,
        "promoter_holding_pct": 52.9, "promoter_pledge_pct": 0.0,
        "dividend_years": 10, "dividend_yield": 0.35,
        "price_flat_months": 8, "profit_growing": True, "volume_rising": False,
        "is_defensive_sector": False,
    },
]


def seed_stocks(db: Session) -> int:
    existing = db.query(Stock).count()
    if existing > 0:
        return existing

    for data in SEED_STOCKS:
        db.add(Stock(**data))
    db.commit()
    return len(SEED_STOCKS)
