apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-sqlite-pvc
  namespace: realworld
  labels:
    app: backend
    app.kubernetes.io/part-of: realworld
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
